services:
  oradock:
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    container_name: cx_oracle_dock
    volumes:
      - oradata:/opt/oracle
    
volumes:
  oradata:
    driver: local
    driver_opts:
      type: none
      device: "$PWD/oracle"
      o: "bind"
